export const MOCK_PRODUCTS = [
  {
    id: "p1",
    name: "Premium Wireless Headphones",
    category: "Electronics",
    status: "ACTIVE",
    variantCount: 6,
    totalStock: 142,
    price: 89.99,
    createdAt: "2025-01-15",
  },
  {
    id: "p2",
    name: "Vintage Leather Jacket",
    category: "Clothing",
    status: "ACTIVE",
    variantCount: 12,
    totalStock: 48,
    price: 249.0,
    createdAt: "2025-01-20",
  },
  {
    id: "p3",
    name: "Organic Green Tea Set",
    category: "Food & Beverage",
    status: "DRAFT",
    variantCount: 3,
    totalStock: 0,
    price: 34.5,
    createdAt: "2025-02-01",
  },
  {
    id: "p4",
    name: "Mechanical Keyboard RGB",
    category: "Electronics",
    status: "INACTIVE",
    variantCount: 4,
    totalStock: 22,
    price: 129.99,
    createdAt: "2025-02-10",
  },
  {
    id: "p5",
    name: "Yoga Mat Pro Series",
    category: "Sports",
    status: "ACTIVE",
    variantCount: 5,
    totalStock: 87,
    price: 59.99,
    createdAt: "2025-02-18",
  },
];
